# -*- mode: python ; coding: utf-8 -*-
"""
Universal Library (UL) - PyInstaller Spec File

Build command:
    pyinstaller build_spec.spec

Output:
    dist/UniversalLibrary/
        UniversalLibrary.exe
        _internal/
        storage/  (created by build.bat)
"""

import os
from pathlib import Path

block_cipher = None

# Get the project root directory
PROJECT_ROOT = Path(SPECPATH)

# Data files to include
datas = [
    # Application icon (for window/taskbar icon at runtime)
    (str(PROJECT_ROOT / 'Icon.png'), '.'),

    # Icons (SVG files for UI)
    (str(PROJECT_ROOT / 'universal_library' / 'widgets' / 'icons'),
     'universal_library/widgets/icons'),

    # UL Blender plugin (for addon installer feature)
    (str(PROJECT_ROOT / 'UL_blender_plugin'), 'UL_blender_plugin'),

    # Addon installation script (for Blender to run)
    (str(PROJECT_ROOT / 'universal_library' / 'services' / 'utils' / 'install_addon.py'),
     'universal_library/services/utils'),
]

# Version file (generated by build.bat)
version_file = PROJECT_ROOT / 'universal_library' / 'version.txt'
if version_file.exists():
    datas.append((str(version_file), 'universal_library'))

# Hidden imports that PyInstaller might miss
hiddenimports = [
    # PyQt6 modules
    'PyQt6.QtCore',
    'PyQt6.QtGui',
    'PyQt6.QtWidgets',
    'PyQt6.QtSvg',
    'PyQt6.QtSvgWidgets',

    # Standard library modules that might be dynamically imported
    'json',
    'sqlite3',
    'logging.handlers',
    'pathlib',
    'typing',
    'hashlib',
    'shutil',
    'datetime',
    'uuid',

    # Universal Library modules
    'universal_library',
    'universal_library.main',
    'universal_library.config',
    'universal_library.widgets',
    'universal_library.widgets.main_window',
    'universal_library.widgets.dialogs',
    'universal_library.widgets.dialogs.setup_wizard',
    'universal_library.widgets.dialogs.about_dialog',
    'universal_library.widgets.dialogs.version_history_dialog',
    'universal_library.widgets.dialogs.scan_progress_dialog',
    'universal_library.services',
    'universal_library.services.database_service',
    'universal_library.services.asset_repository',
    'universal_library.services.thumbnail_service',
    'universal_library.services.watcher_service',
    'universal_library.themes',
    'universal_library.themes.theme_manager',
    'universal_library.themes.dark_theme',
    'universal_library.themes.light_theme',
    'universal_library.models',
    'universal_library.models.asset_list_model',
    'universal_library.views',
    'universal_library.views.asset_card_delegate',
    'universal_library.utils',
    'universal_library.events',
    'universal_library.core',
]

a = Analysis(
    [str(PROJECT_ROOT / 'run.py')],
    pathex=[str(PROJECT_ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude unused modules to reduce size
        'tkinter',
        'matplotlib',
        'numpy.testing',
        'scipy',
        'pandas',
        'cv2',  # Not needed for this project
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='UniversalLibrary',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # No console window (windowed mode)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Note: Using PNG instead of ICO - PyInstaller can convert on Windows
    # For best results, convert Icon.png to UL.ico
    icon=str(PROJECT_ROOT / 'Icon.png'),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='UniversalLibrary',
)
